### ISSUE TITLE
Is Peek defined correctly?

### ISSUE THREAD

**Issue by rwillett** [gbarr/perl-beanstalk-client#9]
Hi,

We've just installed the beanstalkd queue system and are using your Perl client library, thanks very much for it.

We've actually implemented quite a lot in less than 24 hours using both your library and beanstalk, its rather impressive as to what can be done.

One utility we were trying to write was something to clear all the tubes out. We've been throwing tens of gigabytes of data into the system to see how it stresses and it seems to handle X0,000 messages each of 5-10MB without causing any issues. Rather than processing the messages, we thought we'd delete them directly from the tubes.

As far as we can see we need the job id to be able to delete something from the tubes without processing it, but we can't see anything in your perl client to get the job id.

We've looked in the beanstalkd protocol docs and can see this

```
Other Commands
--------------

The peek commands let the client inspect a job in the system. There are four
variations. All but the first operate only on the currently used tube.

 - "peek <id>\r\n" - return job <id>.
```

Your Perl code for the peek command seems to want to have the job id passed into it, rather than returning it. We've looked at your Perl code as well and can see that it is expecting an argument to be passed in. 

Have we misunderstood the point of your peek code? is there an other way of getting the job id? 

We know we can write expect scripts onto telnet session, but thats rather an 1980's day of doing things. We'd much rather use Perl than try to remote how expect works :)

Thanks again,

Rob

**Comment by richardjharris** [comment]
The `peek_ready`, `peek_delayed` and `peek_buried` methods can be used to retrieve the next job in the queue matching those critieria. They don't take an ID.

When clearing out a tube you most likely want to use `reserve`, as you can only delete jobs that are either in ready state, buried or reserved by your client (that is, the same TCP connection). If you use `peek_ready` it is possible that the job will be reserved by another client after your peek_ready call, causing the delete to fail.

**Comment by rwillett** [comment]
Richard,

Thanks for this. We resolved this many months ago by using an expect script with telnet. 

I should have closed it. I will now.

Rob
